[BACK-50] get founders of a github repository
jst-seminar-rostlab-tum/truffle-ai-backend pull request #29
Opened 2023-05-29 09:47 UTC by jonassuess

### Description of Issue
Fetching the github commit history to return an array of Founders with their names, login names and twitter handles. This method goes trough the commit history of a specific repo and fetches teh first 5 commits, which are most likley the initiators of a project. It then removes duplicates, because several commits can be from the same person, but shouldn't be returned within the Array
### How I implemented
Build a GraphQL query and a method to filter out duplicates
### Other
None

2023-05-29 11:14 UTC, thomas-woehrle requested changes
Very good job. 
Only minor changes needed.

2023-05-29 11:14 UTC, thomas-woehrle commented on packages/graphql_server/src/api/githubApi.ts
> +export async function getRepoFounders(owner: string, name: string): Promise<ProjectFounder[]> {
When an invalid values like an empty string is passed an exception is thrown. Please fix this and let it display a suitable message on console.error instead f.e. "Founders of <reponame> owned by <ownername> could not be found"

2023-05-29 11:14 UTC, thomas-woehrle commented on packages/graphql_server/src/api/githubApi.ts
> +type ProjectFounder = {
Refactor types into a separate file in the types folder named `githubApi.types.ts`

2023-06-01 08:46 UTC, thomas-woehrle approved these changes
ProjectFounder type could be GitHubUser type as well, but I can change it with the next version of dbUpdater

2023-06-01 10:03 UTC, pczern requested changes

2023-06-01 10:03 UTC, pczern commented on packages/graphql_server/src/api/githubApi.ts
> +  response.data.data.repository.defaultBranchRef.target.history.edges.forEach((node) => {
response?.data?.data everywhere, also check for existing edges or throw error, also make sure to use optional chaining below

2023-06-08 22:49 UTC, kigadye approved these changes
Looks good

2023-06-09 15:57 UTC, pczern approved these changes
Please read about optional chaining before merging

2023-06-10 05:42 UTC, merged