[Back 53]Implement ELI5, changeOpenAI, implement categories
jst-seminar-rostlab-tum/truffle-ai-backend pull request #32
Opened 2023-05-30 18:58 UTC by acreturs

###Description: Implement description/ELI5 regarding the sentiment towards the project
###How I implemented: A file that contains all the chatGPT methods and a file that scrapes hackernews. 
###Other I am currently working on the categorization wihtin the same branch. Sorry. But I am still struggleing with the types  

In ScrapeRepoCategroies there is still a problem with the types (not eslint confirm) but since we need the functionality I will commit it know and modify it later. But I am just not able to to write the correct types for the complex response. There are prototypes within the types folder.

2023-05-31 08:00 UTC, thomas-woehrle requested changes
I did not take a thorough look at everything, because the duplicates are disturbing.
The hackernews sentiment stuff is good work!

Please address the requested changes or answer if you have another notion. 

Then I will do the second review and look at everything again

**Also: run prettier via npm run format -> your build might fail because of this**

2023-05-31 16:16 UTC, acreturs commented on packages/graphql_server/types/hackerNews.d.ts
> +  export type HackerNewsStoriesResponseHitsArray = {
no because otherwise eslint will throw errors

2023-06-01 08:52 UTC, thomas-woehrle commented
run `npm run format` in the root folder `truffle-ai-backend`. 
Your build might be failing because of this

2023-06-02 07:09 UTC, pczern commented
@acreturs 
> [warn] Code style issues found in 4 files. Forgot to run Prettier?

2023-06-07 13:47 UTC, thomas-woehrle submitted a review, later dismissed
Good improvements. 

Additionally to everything I said in my comments please add for each of the files that you added a file called `<filename>.test.ts` into the `/src/test` folder where you show possible invoactions of the methods. Look at the `dbUpdater.test.ts` file to see what i mean.

2023-06-07 13:47 UTC, thomas-woehrle commented on packages/graphql_server/src/api/openAIApi.ts
Please add comments to the functions. One at the top of the function in the format specified on the Notion page (->LaFamiglia->Backend->Information->Documentation guidelines) and multiple smaller ones inside the code explaining what you are doing

2023-06-07 13:47 UTC, thomas-woehrle commented on packages/graphql_server/src/api/openAIApi.ts
> +const postURL = 'https://api.openai.com/v1/chat/completions'
maybe rename this to `openAIapiUrl`. you can use f2 to rename a variable and its occurences in vscode

2023-06-07 13:47 UTC, thomas-woehrle commented on packages/graphql_server/src/scraping/hackerNewsScraper.ts
rename to hackerNewsScraping.ts

2023-06-07 13:47 UTC, thomas-woehrle commented on packages/graphql_server/src/scraping/scrapeGithubCategories.ts
please move the function to the `githubApi.ts` file. It really only calls the api -> no scraping. 
After moving it to the githubApi.ts file you can delete this file

2023-06-07 13:47 UTC, thomas-woehrle commented on packages/graphql_server/types/hackerNews.d.ts
rename this file to `hackerNewsScraper.d.ts` , even if its types are used somewhere else as well

2023-06-07 17:46 UTC, thomas-woehrle requested changes
Sorry but you could please revise the test files. 

Right now all of the test functions are logging promises. 
Also please let the test functions take as parameters the parameters that the corresponding functions would take. I just want to write a single line of code to test it, because it takes a lot of time already to do reviews. 
F.e. the function testHackernewsScraping should take as parameter the parameter that searchHackernewsStory takes in and should log onto the console the result.

In the case of testHackerNewsSentiment, which also needs the readme you can decide on whether or not to pass arguments to the test function, since then you would have to get readme first. 

Write me if you have any questions.

2023-06-11 12:45 UTC, pczern approved these changes

2023-06-12 06:40 UTC, thomas-woehrle commented
I changed some small things. @acreturs sorry I falsely wrote you to delete githubScraping. What I actually wanted was to just delete one funciton of it. I restored it to how it should be though

2023-06-12 06:41 UTC, thomas-woehrle approved these changes

2023-06-12 06:41 UTC, merged