Back 51
jst-seminar-rostlab-tum/truffle-ai-backend pull request #33
Opened 2023-05-30 20:53 UTC by 2015builder

###Description: Added the new ContributorCount
###How I implemented: New method how Clemens explained it. Get the names of all people that made a commit to the main branch and eliminate duplicates
###Other

2023-05-31 06:27 UTC, thomas-woehrle requested changes
Great job, just small things.
Your build fail message indicates that you did not run prettier. You can so with` npm run format`.

2023-05-31 06:27 UTC, thomas-woehrle commented on packages/graphql_server/src/types.ts
I have already refactored all of these types into the respective files of the `/types` folder and updated the imports that existed before your PR.
So delete this file and update the imports where/if needed, thanks

2023-05-31 06:27 UTC, thomas-woehrle commented on packages/graphql_server/src/scraping/githubScraping.ts
I would move it into the api/githubApi.ts file.
I think there is no scraping going on but rather an API call

2023-05-31 06:27 UTC, thomas-woehrle commented on packages/graphql_server/types/githubScraping.d.ts
If you move the other file to `/api/githubApi.ts`, please move these types into the corresponding types file as well, thanks

2023-05-31 10:07 UTC, cnk1dev requested changes
Refactor according to @thomas-woehrle's comments & run prettier to pass GitHub tests, rest looks good.

2023-05-31 10:07 UTC, cnk1dev commented on packages/graphql_server/src/scraping/githubScraping.ts
> +          Authorization: `Bearer ` + authToken
```suggestion
          Authorization: `Bearer ${authToken}`
```

2023-06-01 08:28 UTC, thomas-woehrle commented
I merged main

2023-06-01 08:29 UTC, thomas-woehrle approved these changes

2023-06-01 10:00 UTC, pczern requested changes

2023-06-01 10:00 UTC, pczern commented on packages/graphql_server/src/api/githubApi.ts
> +  try {
don't catch errors, so we can catch them in the GraphQL resolvers and give appropriate feedback and logging where due

2023-06-02 07:08 UTC, pczern approved these changes

2023-06-02 09:04 UTC, cnk1dev approved these changes

2023-06-02 10:17 UTC, merged