[BACK-16] Manual addition of repositories to truffle
jst-seminar-rostlab-tum/truffle-ai-backend pull request #35
Opened 2023-06-01 07:15 UTC by thomas-woehrle

### Description of Issue
FR8 says:
_I can manually add entities, so Truffle AI can help me track them along with the most relevant ones
(e.g. when Truffle AI does not spot it automatically)._
### How I implemented
- adapted the schema
- added resolvers
- let chatGPT create a function for transforming the url into name and owner and fine-tuned that function
- tested
### Other
- in the resolvers i used unknown type and skipped the first argument passed to the resolver function
- Can be accessed via: 
`mutation {
   addProjectByName(name: "name", owner: "owner")
}`
- during implementation small issues with the current version of dbUpdater got apparent. While fix those in the future

2023-06-02 07:05 UTC, pczern requested changes

2023-06-02 09:09 UTC, cnk1dev commented on packages/graphql_server/src/graphql/resolvers.ts
@pczern idk is that usually done?

2023-06-02 09:09 UTC, cnk1dev approved these changes
Should be good to go after addressing @pczern's comment

2023-06-04 15:25 UTC, thomas-woehrle commented on packages/graphql_server/src/graphql/resolvers.ts
> +      const urlParts = parseGitHubUrl(url)
@pczern Let's keep it simple for now -> true if inserting works, false if it doesn't

2023-06-04 15:25 UTC, thomas-woehrle commented on packages/graphql_server/src/graphql/resolvers.ts
> +      const urlParts = parseGitHubUrl(url)
@pczern what do you mean with "check for all parts" ?

2023-06-05 19:02 UTC, thomas-woehrle commented
@pczern anything new regarding this PR ? I responded to your comment

2023-06-06 10:27 UTC, pczern commented on packages/graphql_server/src/graphql/resolvers.ts
Not sure about that. But it makes sense to have a central place to decide which error messages are getting exposed, the resolvers here are a way to do this. If we didn't catch an error earlier, we might be exposing data we don't want to expose. More if we catched an error earlier, we might not have propagated the underlying error message; but a more generic message that makes debugging hard.

2023-06-06 10:28 UTC, pczern approved these changes

2023-06-07 13:12 UTC, merged