[BACK-68] Get number of contributors for a given repository
jst-seminar-rostlab-tum/truffle-ai-backend pull request #42
Opened 2023-06-12 10:43 UTC by acreturs

###Get the Contributor Count for a given Repository 

###A simple rest call to find the repository contributors

2023-06-12 18:44 UTC, kigadye approved these changes
Improve comments, otherwise good

2023-06-14 07:04 UTC, thomas-woehrle requested changes
good job on the test file.

But the function does not do what it is supposed to. As the description of the Linear task says it should return the number of contributors. Instead it seems like it returns the top 30 contributors. Your request probably only fetches the first 30 entries of the contributors. 

So rewrite the function to return the number of contributors. You should also put the function into the file githubApi.ts because scraping != calling an API.

The link I mentioned in the linear task also shows a way to only use one api call instead of counting all the individual contributors. Maybe this works still if not find a different way.

2023-06-15 09:28 UTC, thomas-woehrle requested changes
Small things. I also did a commit to get rid of the console.log statements and to replace the old getContributorCount method with yours. 
So pull before continue working. 
Also add authorization!

2023-06-15 09:33 UTC, acreturs commented on packages/graphql_server/src/api/githubApi.ts
> +    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
For some reason I still get any. I will just receive it as a string.

2023-06-15 09:33 UTC, acreturs commented on packages/graphql_server/src/api/githubApi.ts
> +    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
const linkHeader: string = response?.headers?.link as string

2023-06-15 09:33 UTC, acreturs commented on packages/graphql_server/src/api/githubApi.ts
> +    const response = await axios.get(`https://api.github.com/repos/${owner}/${repo}/contributors`, {
you mean for the response?

2023-06-15 15:26 UTC, acreturs commented on packages/graphql_server/src/api/githubApi.ts
> +        per_page: 1
I am not sure how to add anon as a parameter

2023-06-15 16:55 UTC, thomas-woehrle approved these changes
Nice job Alex!

2023-06-15 16:56 UTC, merged