[BACK-70] Refactoring and fixes of dbUpdater
jst-seminar-rostlab-tum/truffle-ai-backend pull request #53
Opened 2023-06-16 10:52 UTC by thomas-woehrle

### Description of the issue
- refactor the files dbUpdater.ts, processRepo.ts and dataAggregation.ts
- organizations without existing projects should be deleted
- associated persons without projects or foundings should be deleted

### How I implemented
- Redistributed functions that reside in dbUpdater, processRepo and dataAggregation, because they did not really belong where they were
- renamed `processRepo.ts` to `updateProject.ts` and `dataAggregation.ts` to `supabaseUtils.ts`
- introduced new file `utils.ts` 
- adjusted the corresponding types files names
- .... tbd

### Other
Branched from my current PR BACK-58. Will merge this file into there as well probably

2023-06-17 09:13 UTC, ArnoClaude requested changes

2023-06-17 09:13 UTC, ArnoClaude commented on packages/graphql_server/src/api/openAIApi.ts
> +  if (comments.length > 5000) {
`5000` should probably be a `const` called `GPT_MESSAGE_LIMIT` or something instead of a magic number :)

2023-06-17 17:44 UTC, kigadye approved these changes
Didn't find any bugs, code quality is really good. I think you could refactor the codebase even further though, there's still a lot of huge files that can be split up and a lot of info logs that are not really necessary. I've seen some projects that used console.info for info logs and then configured the logger in a way that on prod only errors are logged but idk if that comes out of the box with node or requires a third party logger.

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/api/openAIApi.ts
>  // eslint-disable-next-line @typescript-eslint/no-unused-vars
```suggestion
```

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/dbUpdater.ts
> +*/
```suggestion
```

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/dbUpdater.ts
> + * It updates old projecst and inserts new trending ones.
```suggestion
 * Updates old projects and inserts new trending ones.
```

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/dbUpdater.ts
> +    )
```suggestion
```

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/dbUpdater.ts
> +      console.log('inserted project', repoName, 'owned by', owner)
```suggestion
```

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/dbUpdater.ts
> +    )
too many info logs on prod server will make it very hard to debug errors

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/utils.ts
create utils folder and put each function into a separate file

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/supabaseUtils.ts
this file is way too big, split up functions into individual files

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/supabaseUtils.ts
> +*/
```suggestion
```

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/test/dbUpdater.test.ts
>    console.log('error occured')
```suggestion
```
console.error already implies that it's an error

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/test/dbUpdater.test.ts
>    console.log('error occured')
```suggestion
```
console.error already implies that it's an error

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/updateProject.ts
> +    updated && console.log('updated eli5 of ', name, 'owned by', owner)
```suggestion
```

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/updateProject.ts
> +    console.log('Could not get github stats for ', name, 'owned by', owner)
```suggestion
    console.error('Could not get github stats for ', name, 'owned by', owner)
```

2023-06-17 17:44 UTC, kigadye commented on packages/graphql_server/src/updateProject.ts
> +  }
```suggestion
  if (!updated) {
    console.error('Could not update github stats for ', name, 'owned by', owner)
  }
```

2023-06-18 08:28 UTC, acreturs approved these changes
Could not test the functionality since there is currently a problem on my machine. But the code looks well structured and according to the guidelines

2023-06-18 14:22 UTC, merged