[BACK-95] Fix bookmark deletion bug
jst-seminar-rostlab-tum/truffle-ai-backend pull request #74
Opened 2023-07-10 15:47 UTC by thomas-woehrle

### Description of the issue
Non-Trending bookmarks are deleted by the repo_job. That is because the is_bookmarked attribute is updated, but a piece of old code sets the is_bookmarked state to false, when updating the GitHub stats. 

### How I implemented
- removed `is_bookmarked: false` from `formatGithubStats()`

additionally i made the following small adjustments while I was at it:
- changed `void` to `await` when adding bookmark after manual addition. This slightly increases response time but might be needed, if the frontend wants to render new bookmarks right away in the future.
- removed some comments and logs
- removed the linkedIn data fetching method since we canceled our plan

### Other
- I restored the db backup from Saturday evening
- I changed all is_bookmarked states of the currently bookmarked projects to is_bookmarked via a function run on my machine
- I (temporarily) added BACK-95 to the deploy script because the currently deployed version would override the is_bookmarked states again at the next full hour.

2023-07-10 18:51 UTC, kigadye approved these changes

2023-07-11 11:57 UTC, pczern requested changes

2023-07-11 11:57 UTC, pczern commented on .github/workflows/deploy.yml
bad

2023-07-11 14:18 UTC, thomas-woehrle commented on .github/workflows/deploy.yml
I specifically described why I did this in the description. I will remove this line

2023-07-12 09:34 UTC, merged